config/routes.rb
Goodinc::Application.routes.draw do

  resources :organizations, :only=>[:index, :show, :edit, :update] do
    resources :users do
      member do
        get :reset_password
        get :welcome
      end
    end
    resources :posts, :only => [:create, :destroy, :update] do
      member do
        get :delete
      end
    end
  end

  post "contents/search_resources" => "contents#search_resources", :format=>:js

  resources :applications

  get "/randompartner" => 'pages#randompartner'
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "my_account" => "users#my_account"
  put "update_account" => "users#update_account"

  resources :password_resets

  get '/activity', :controller => 'nominations', :action => 'activity'

  resources :nominations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "welcome/index"



  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#index"
  get "search/donates" => "search#donates"
  get "search/opportunities" => "search#opportunities"

  get "versions/:id/revert" => "versions#revert", as: :version_revert

  resources :users
  resources :sessions

  get "sessions/new"
  get "users/new"

  # Should stay at the bottom so it doesn't clobber any other routes
  match "/page/:slug", :controller=>:pages, :action=>:show, :as=>"page"

  get 'contact_us', :controller => 'contacted_organizations', :action => 'index', :as => :contactus
  post 'contact_us', :controller => 'contacted_organizations', :action => 'save_contact_us', :as => :save_contact_us

  unless Rails.env.production?
    mount UserMailer::Preview => 'email_preview'
  end


  root :to => 'pages#index'

end

app/models/application.rb
class Application < ActiveRecord::Base

  attr_accessible :id, :user_id, :primary_commitment, :collab_org, :description, :commitmentcat
  attr_accessible :year1, :year2, :year3, :year4, :year5, :org_commitment_type, :further_info, :add_info, :is_consent, :secondary_id, :vetting_id
  attr_accessible :supp_commitment, :supp_add_commitment, :supp_add_commitemnt_cat, :supp_year1, 
                  :supp_year2, :supp_year3, :supp_year4, :supp_year5, :supp_commitment_type, :supp_launch, :supp_further_info, :supp_add_info

  attr_accessible :avatar, :remote_avatar_url, :remove_avatar, :avatar_cache
  
  mount_uploader :avatar, AvatarUploader

  belongs_to :secondary
  belongs_to :user
  has_many :vettings
  
  
  scope :submitted, where(:is_submitted=>true)
  
  def status
    stale_vettings=self.vettings.where(["updated_at < ?", self.updated_at])
    
    statuses=self.vettings.collect {|v| v.status}
    statuses=statuses.compact.uniq
    
    case
      when stale_vettings.any?
        "RESUBMITTED" 
      when statuses.empty?, statuses.include?('PENDING')
        "PENDING"
      when statuses.include?('SECOND_REVIEW')
        "REVIEW"
      when statuses.include?('REJECTED')
        "REJECTED"
      when statuses.include?('APPROVED')
        "APPROVED"
      else
        "UNKNOWN"
      
    end      
  end
  
end
# == Schema Information
#
# Table name: applications
#
#  id                      :integer         not null, primary key
#  user_id                 :integer
#  primary_commitment      :text
#  collab_org              :text
#  description             :text
#  commitmentcat           :string(255)
#  year1                   :text
#  year2                   :text
#  year3                   :text
#  year4                   :text
#  org_commitment_type     :string(255)
#  further_info            :text
#  add_info                :text
#  avatar                  :string(255)
#  is_consent              :boolean
#  secondary_id            :integer
#  vetting_id              :integer
#  created_at              :datetime
#  updated_at              :datetime
#  is_submitted            :boolean         default(FALSE)
#  supp_commitment         :text
#  supp_add_commitment     :text
#  supp_add_commitemnt_cat :string(255)
#  supp_year1              :text
#  supp_year3              :text
#  supp_year5              :text
#  supp_commitment_type    :string(255)
#  supp_launch             :string(255)
#  supp_further_info       :text
#  supp_add_info           :text
#  supp_year2              :text
#  year5                   :text
#  supp_year4              :text
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from ActionView::MissingTemplate, :with => :rescue_template
  rescue_from ActionController::RoutingError, :with => :rescue_404
  rescue_from ActiveRecord::RecordNotFound, :with => :rescue_404
  rescue_from ActionDispatch::ClosedError, :with => :rescue_closed
  helper_method :all_top_posts_of_organizations
  helper_method :all_posts
  helper :pages
  def all_posts
    posts.find(:all, :order=> 'created_at desc')
  end

  #$all_top_posts = all_top_posts_of_organizations

  # Added on 10-Mar-2012 to fetch all top posts from each organization
  # Start
  def all_top_posts_of_organizations
    posts = Hash.new
    @top_posts_by_org = Post.select("organization_id as org_id, max(created_at), max(id) as post_id").group("organization_id").order('max Desc').page(params[:page]).per(5)
  end
  #End adding method all_top_posts_of_organizations

  def not_authenticated
    if request.flash[:notice]
      redirect_to login_url, :notice => request.flash[:notice]
    else
      redirect_to login_url, :alert => "First login to access this page."
    end
  end

  def current_ability
    @current_ability ||= Ability.new(current_admin_user || current_user)
  end

  rescue_from CanCan::AccessDenied do |exception|
    if current_admin_user
      redirect_to admin_dashboard_path, :alert => exception.message
    else
      redirect_to welcome_index_path, :alert => exception.message
    end
  end

  def rescue_template
    redirect_to root_path
  end

  def rescue_404
    redirect_to root_path
  end

  def rescue_closed
    redirect_to root_path
  end


end

app/controllers/applications_controller.rb
class ApplicationsController < InheritedResources::Base

  def create

    @application = Application.where(:user_id=>current_user.id).first

    if @application.present?
      update_application
    else
      save_application
    end

    respond_with() do |format|
      format.html {
       if ( params[:application][:type]=="submit")

          unless @application.is_submitted?
            @application.update_attribute('is_submitted',true)
            UserMailer.delay.nominator_application_submission_notice(@application)
            #TODO: reset vetting status
          end

          #Make sure we touch the updated_at timestamp each time the application is submitted, even if already submitted
          @application.touch

          flash[:notice] = "Your application has been successfully submitted."
          render :template=>"/applications/thanks"


       else
          redirect_to root_path, :notice =>"Your application has been successfully saved."
       end
      }
    end
  end

  private

  def update_application

    @user = User.where(:id=>current_user.id).first
    @user.attributes = params[:user]
    @user.save

    @organization = Organization.where(:id=>current_user.organization_id).first
    @organization.attributes = params[:organization]
    @organization.save

    @application.attributes = params[:application]
    @application.save

    if (@application.secondary_id.present?)
      @secondary = Secondary.where(:id=>@application.secondary_id).first
    else
      @secondary = Secondary.new
    end
    @secondary.attributes = params[:secondary]
    @secondary.save

    @application.update_attribute('secondary_id',@secondary.id)
    @application.update_attribute('user_id',@user.id)

  end

  def save_application

    @user = User.where(:id=>current_user.id).first
    @user.attributes = params[:user]
    @user.save

    @organization = Organization.where(:id=>current_user.organization_id).first
    @organization.attributes = params[:organization]
    @organization.save

    @application = Application.new
    @application.attributes = params[:application]
    @application.save

    @secondary = Secondary.new
    @secondary.attributes = params[:secondary]
    @secondary.save

    @application.update_attribute('secondary_id',@secondary.id)
    @application.update_attribute('user_id',@user.id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)  
    Redcarpet.new(text, :autolink, :hard_wrap).to_html.html_safe  
  end  
  
  def format_breaks(text)
    text.gsub(/\r\n/, '<br>').html_safe
  end
  
  def is_active?(page_name)
    "menu_current_selected" if params[:action] == page_name && current_user.organization == @organization
  end

  def contactus_reasons
    array_of_reasons = []
    reasons = Content.insert "contact_us_reasons"
    if reasons.include?(',')
      parsed_object = reasons.split(',')
      parsed_object.each do |str|
        array_of_reasons << strip_tags(str)
      end
    else
      nokogiri_object = Nokogiri::HTML(reasons)
      parsed_object = nokogiri_object.xpath('//text()').text
      stripped_object = parsed_object.strip.scan(/\w+.*/i)
      stripped_object.each do |object|
        array_of_reasons << object.strip
      end
    end
    return array_of_reasons
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper

  def cool_heading(heading)
    header = raw heading.strip.gsub('&', '<span class="contrast">&</span>')
  end

end

app/views/applications/_faq.html.haml
%img{:alt => "Header Faq", :height => "58", :src => "/assets/header-faq.png", :width => "630"}/
.contentShell
  %p The following FAQs were developed in response to recent questions and inquiries we have received from past 100Kin10 nominees. We hope you will find them helpful and continue to reach out with your questions.
  %p.question 1. What does success look like, and how do you intend to grow over time?
  %p.answer
    The simplest and most specific answer is that we aim to respond to the nation’s need for 10,000 new, excellent STEM teachers over 2 years and 100,000 over 10 years, working closely with partner organizations as well as the Department of Education and the White House to ensure positive, measurable growth. The purpose is to reverse our country’s decades-long decline in STEM subjects, to ensure that all children have the basic STEM literacy to be full participants in our economy and democracy, and to enable our country’s students to address the most pressing national and global challenges.
    %br/
    %br/
    We are mobilizing an expanding, multi-sector group of organizations to strategically apply its collective assets in a coordinated way to solve a complex, national problem. We are doing this by creating an “enlightened marketplace” that doesn’t rely on any centralized entity having all the answers to complex questions related to teacher preparation or local demand for STEM talent. Instead, funders with their own expertise can identify and partner with pre-vetted organizations with deep knowledge of local, statewide, and national needs.

  %p.question 2. How does 100Kin10 focus on quality?
  %p.answer
    100Kin10 is not just about numbers. The movement is focused on excellence. The true end goal is to dramatically increase the number of excellent STEM teachers so that all students have access to first-rate STEM learning. UEI oversees the 100Kin10 vetting process to ensure that accepted partners have both high-quality commitments and the capacity to execute them with excellence. Additionally, UEI is developing a learning and R&D infrastructure, as well as tools for 100Kin10partners to measure the quality and impact of their commitments. Throughout the next years, UEI will undertake regular, rigorous reviews of all programs, will provide real-time feedback on implementation, and will share best practices to drive improvement across 100Kin10 partners and the STEM teaching field at large.

  %p.question 3. Is the focus just on recruiting new teachers?
  %p.answer No. Though increasing the number of new, excellent STEM teachers in the pipeline is important, 100Kin10 recognizes that to achieve these ambitious goals we also need to keep our best STEM teachers in the classroom and encourage commitments that change the circumstances in which STEM teachers work—from how they are recruited, hired, evaluated, and paid to the support they receive and the opportunities they have to grow in their careers.
  
  %p.question 4. What are "bold" commitments?
  %p.answer Bold commitments are creative and innovative responses to our shared goal of 100,000 excellent STEM teachers in 10 years. They reflect new or expanded approaches to tackling this challenge through INCREASING THE SUPPLY of excellent STEM teachers, DEVELOPING and RETAINING excellent STEM teachers, and/or BUILDING THE 100Kin10 MOVEMENT – all while leveraging the unique assets of your organization.
  
  %p.question 5. Are all partners automatically eligible for funding?
  %p.answer To become eligible for funding, partners must complete a common proposal application form that will be reviewed by each funding partner. Application forms and further information on the funding process will be available in late 2011. Decisions regarding funding are made independently by each funding partner.
  
  %p.question 6. How can I become a funding partner?
  %p.answer Potential funders enter the movement through a separate process and do not need to complete an online application form. If you are interested in joining the funders' collaborative, please contact Talia Milgrom-Elcott at tme@carnegie.org.
  
  %p.question 7. How is 100Kin10 different from other groups working on STEM education?
  %p.answer 100Kin10 is a growing movement to respond to the national imperative to train 100,000 new, excellent STEM teachers over the coming 10 years. It is neither a paper coalition of similarly-minded allegiances nor a command-and-control, centralized effort. Instead, it is an effort to invite a wide array of players—from federal agencies to states, museums to corporations, universities to school districts, individuals to associations—to identify their assets and apply them creatively and strategically to solving one of our country’s most vexing challenges: how to give every child a first-rate STEM education so that we can regain our competitive edge in the STEM fields and address the national and global challenges that will define this century.
  
  %p.question 8. In our application, do we need to articulate a plan for reaching our commitment?
  %p.answer Applicants should describe their capacity to carry out their commitments. When setting targets for the scope of your commitment, however, we ask that you do not limit yourself to your current funding streams. We understand that the scope of a commitment may change based on funding received. You are welcome to work with the organization that nominated you to develop your commitment, or view the list of current 100Kin10 commitments as a reference.
  
  %p.question 9. Our commitment reflects a partnership among several non-profits, corporations, associations, etc. Can we apply with a commitment from a new or proposed partnership?
  %p.answer We welcome commitments that are designed in partnership. Please specify on your application if other entities are contributing to the commitment.
  
  %p.question 10. We are a small organization. Is there a minimum impact number you’re looking for in a strong commitment?
  %p.answer We seek strong partner organizations of all sizes, with bold and significant commitments.

  %p.question 11. When and how do we apply?
  %p.answer The deadline for online submissions is 11:59PM EST November 25th, 2011.

  %p
    For additional information about 100Kin10, please visit 100kin10.org or e-mail
    %a{:href => "mailto:info@100kin10.org"} info@100kin10.org
/ end contentShell

app/views/applications/_index.html.haml
#contentnav
  -if @current_user
    -if @current_user.is_nominator
      %ul.tabs
        / Give href an ID value of corresponding "tabs-content" <li>'s
        %li
          %a{:href => "#community"} Community
        %li
          %a{:href => "#resources"} Resources
        %li
          %a.active{:href => "#nomination"} Nomination
    -else
      %ul.tabs
        / Give href an ID value of corresponding "tabs-content" <li>'s
        %li
          %a.active{:href => "#welcome"} Welcome
        %li
          %a{:href => "#faq"} FAQs
        %li
          %a{:href => "#application"} Application 

%ul.tabs-content
  / Give ID that matches HREF of above anchors
  %li#welcome.active
    =render '/applications/welcome'
  %li#faq
    =render '/applications/faq'

app/views/applications/_welcome.html.haml
%img{:alt => "Your Nomination", :height => "58", :src => "/assets/header-your-nomination.png", :width => "630"}/
.contentShell
  %h1 Thank you for your applications.
  %p The application period ended on December 2nd at 11:59PM EST.
  %p If you have any questions, please contact our team directly at info@100Kin10.org.
  %br
  %p Thanks, The 100Kin10 Team

app/views/applications/edit.html.haml
%h1 Editing application

= render 'form'

= link_to 'Show', @application
\|
= link_to 'Back', applications_path

app/views/applications/new.html.haml
%h1 New application

= render 'form'

= link_to 'Back', applications_path

app/views/applications/show.html.haml
%p#notice= notice

%p
  %b User:
  = @application.user_id
%p
  %b Primary commitment:
  = @application.primary_commitment
%p
  %b Collab org:
  = @application.collab_org
%p
  %b Description:
  = @application.description
%p
  %b Commitmentcat:
  = @application.commitmentcat
%p
  %b Year1:
  = @application.year1
%p
  %b Year2:
  = @application.year2
%p
  %b Year3:
  = @application.year3
%p
  %b Year4:
  = @application.year4
%p
  %b Org commitment type:
  = @application.org_commitment_type
%p
  %b Further info:
  = @application.further_info
%p
  %b Add info:
  = @application.add_info
%p
  %b Avatar:
  = @application.avatar
%p
  %b Is consent:
  = @application.is_consent
%p
  %b Secondary:
  = @application.secondary_id
%p
  %b Vetting:
  = @application.vetting_id

= link_to 'Edit', edit_application_path(@application)
\|
= link_to 'Back', applications_path

app/views/applications/thanks.html.haml
%ul.tabs-content
  / Give ID that matches HREF of above anchors
  %li#welcome.active
    =render '/applications/welcome'
  %li#faq
    =render '/applications/faq'
  %li#application
    %img{:alt => "Application", :height => "58", :src => "assets/header-application.png", :width => "630"}/
    .contentShell
      %h1 Thank You
      %p
        Thank you for submitting an application for partnership in the 100Kin10 movement. Partners will be selected and all applicants notified in January 2012. For further information, please visit 100Kin10.org or e-mail
        %a{:href => "mailto:info@100Kin10.org"} info@100Kin10.org
      %h1 Resubmit Your Application 
      =render "/applications/form"