config/routes.rb
Goodinc::Application.routes.draw do

  resources :organizations, :only=>[:index, :show, :edit, :update] do
    resources :users do
      member do
        get :reset_password
        get :welcome
      end
    end
    resources :posts, :only => [:create, :destroy, :update] do
      member do
        get :delete
      end
    end
  end

  post "contents/search_resources" => "contents#search_resources", :format=>:js

  resources :applications

  get "/randompartner" => 'pages#randompartner'
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "my_account" => "users#my_account"
  put "update_account" => "users#update_account"

  resources :password_resets

  get '/activity', :controller => 'nominations', :action => 'activity'

  resources :nominations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "welcome/index"



  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#index"
  get "search/donates" => "search#donates"
  get "search/opportunities" => "search#opportunities"

  get "versions/:id/revert" => "versions#revert", as: :version_revert

  resources :users
  resources :sessions

  get "sessions/new"
  get "users/new"

  # Should stay at the bottom so it doesn't clobber any other routes
  match "/page/:slug", :controller=>:pages, :action=>:show, :as=>"page"

  get 'contact_us', :controller => 'contacted_organizations', :action => 'index', :as => :contactus
  post 'contact_us', :controller => 'contacted_organizations', :action => 'save_contact_us', :as => :save_contact_us

  unless Rails.env.production?
    mount UserMailer::Preview => 'email_preview'
  end


  root :to => 'pages#index'

end

app/models/nomination.rb
class Nomination < ActiveRecord::Base

  validates :reason, :presence => true 
  validates :nominee_id, :presence => true 
  validates :nominator_id, :presence => true 

  #Doesn't Really Get Set??
  belongs_to :user
  
  belongs_to :nominee, :class_name=>'User', :foreign_key=>:nominee_id
  belongs_to :nominator, :class_name=>'User', :foreign_key=>:nominator_id
  
  liquid_methods :message
  
  
  def save_nomination(nomination, nominee_id, nominator_id)
    self.reason = nomination[:reason]
    self.message = nomination[:message]
    self.nominee_id = nominee_id
    self.nominator_id = nominator_id
    self.save!
    return self
  end
  
end
# == Schema Information
#
# Table name: nominations
#
#  id           :integer         not null, primary key
#  nominator_id :integer
#  nominee_id   :integer
#  reason       :text
#  message      :text
#  status_id    :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/nominations_controller.rb
class NominationsController < InheritedResources::Base

  helper :pages  
  before_filter :require_login
  
  def index 
    @total_nominations = Nomination.where(:nominator_id=>current_user.id).count
  end
  
  def create
    @total_nominations = Nomination.where(:nominator_id=>current_user.id).count

    respond_with() do |format|
      format.html {
        if (params[:preview]=="true")
          params[:preview]=nil
          render :template=>"/nominations/preview"
        end         
      } 
      format.js { 
        
        unless (params[:edit]=="true")

          @nominee_org = Organization.new.save_organization(params[:nominee_organization_name], nil)
          @nominator_org = Organization.new.save_organization(params[:nominator_organization_name], params[:nominator_orgtype])
          
          nominee_password=ActiveSupport::SecureRandom.base64(6)
          @nominee = User.new.save_nominee(params, @nominee_org.id, nominee_password)
          @nominator = User.new.update_nominator(params, @nominator_org.id)
          
          @nomination = Nomination.new.save_nomination(params, @nominee.id, @nominator.id)
          
          UserMailer.delay.nomination_confirmation(@nominee, @nominator, @nomination, nominee_password) 
          UserMailer.delay.nominee_confirmation(@nominee, @nominator, @nomination) 
                    
        end         
      
      } 
    end
  end

# Added on 20-April-2012 to add "Activity" link on the portal 
# Start 
  def activity
    if current_user
       @nominations = Nomination.where("nominator_id = '#{current_user.id}'")
       @organization = current_user.organization
    end
  end
# End
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/views/nominations/_community.html.erb
<%= Content.insert('community_partners') %>

<h3>sort by:  <a href="?order=name">NAME</a>  |   <a href="?order=joined_at">DATE JOINED</a>  |   <a href="?order=orgtype_id">ORG TYPE</a>  |  <a href="?order=state_id">STATE</a>  |  <a href="?order=commitment_category">COMMITMENT CATEGORY</a></h3><br/>


<div class="boxes">

<% Organization.all_partners.order(params[:order]).each do |organization| %>
  
  <div class="float">
    <div class="boxleft">
    <%= link_to organization do %>
      <%= image_tag organization.avatar.grey_tile.url %><br />
    <% end %>
    </div>
    <div class="boxcontent">
    <strong><%= organization.name %></strong><br>
  	<%= organization.orgtype.title if organization.orgtype  %><br>
  	<%= organization.city %>, <%= organization.state.abbreviation if organization.state %><br>
  	<%= organization.joined_at.strftime('%m/%Y') if organization.joined_at %>
  	</div>	
  </div>

<% end %>

<div class="spacer">
  &nbsp;
</div>


</div>

app/views/nominations/_form.html.haml
:javascript
  $(document).ready(function() {
    $("form").validate(function() {
      onkeyup: false;
    });
  });
#errContainer

=form_tag('/nominations?preview=true', :id => 'nomination-form') do

  .formRight

    .fText
      =label_tag 'nominee_organization_name', 'Nominee Organization: *'
      =text_field_tag 'nominee_organization_name',  params[:nominee_organization_name], :class=>'required'

    .fText
      =label_tag 'nominee_first_name', 'Nominee First Name: *'
      =text_field_tag 'nominee_first_name', params[:nominee_first_name], :class=>'required'

    .fText
      =label_tag 'nominee_first_name', 'Nominee Last Name: *'
      =text_field_tag 'nominee_last_name', params[:nominee_last_name], :class=>'required'
      
    .fText
      =label_tag 'nominee_title', 'Nominee Title: *'
      =text_field_tag 'nominee_title', params[:nominee_title], :class=>'required'  

    .fText
      =label_tag 'nominee_phone', 'Nominee Phone: *'
      =text_field_tag 'nominee_phone', params[:nominee_phone], :class=>'required phoneUS'     
                        
    .fText
      =label_tag 'nominee_email', 'Nominee Email: *'
      =text_field_tag 'nominee_email', params[:nominee_email], :class=>'required email'   
      
    %span.fNote
      %b Please note:
      The information below will be shared with the nominee.
      
    .fText
      =label_tag 'nominator_first_name', 'Your First Name: *'
      =text_field_tag 'nominator_first_name', ( (params[:nominator_first_name].present?) ? params[:nominator_first_name] : current_user.first_name ), :class=>'required'

    .fText
      =label_tag 'nominator_last_name', 'Your Last Name: *'
      =text_field_tag 'nominator_last_name', ( (params[:nominator_first_name].present?) ? params[:nominator_last_name] : current_user.last_name ), :class=>'required'
      
    .fText
      =label_tag 'nominator_title', 'Your Title: *'
      =text_field_tag 'nominator_title', ( (params[:nominator_title].present?) ? params[:nominator_title] : (current_user.title if current_user.title.present?) ), :class=>'required'         

    .fText
      =label_tag 'nominator_organization_name', 'Your Organization: *'
      =text_field_tag 'nominator_organization_name',  ( (params[:nominator_organization_name].present?) ? params[:nominator_organization_name] :  (current_user.organization.name if current_user.organization.present?) ), :class=>'required'

    .fText
      =label_tag 'nominator_orgtype', 'Organization Type: *'
      =select_tag 'nominator_orgtype', options_from_collection_for_select(Orgtype.all, "id", "title", ( (params[:nominator_orgtype].present?) ? params[:nominator_orgtype] :  (current_user.organization.orgtype_id if current_user.organization.present?) )), :class=>'required'
                        
    .fText
      =label_tag 'nominator_email', 'Your Email: *'
      =text_field_tag 'nominator_email', ( (params[:nominator_email].present?) ? params[:nominator_email] : (current_user.email if current_user.email.present?) ), :class=>'required email'       

    .fText
      =label_tag 'nominator_phone', 'Your Phone: *'
      =text_field_tag 'nominator_phone', ( (params[:nominator_phone].present?) ? params[:nominator_phone] : (current_user.phone if current_user.phone.present?) ), :class=>'required phoneUS'       
      
  .formLeft
    =label_tag 'reason', 'Reason for nominating organization: * <span>You have <span id="reasonCharsLeft"></span> chars left.</span>'.html_safe
    %br/
    =text_area_tag 'reason', params[:reason], :class=>'required'
    
    =label_tag 'message', 'Personal Message to the Nominee: * <span>You have <span id="messageCharsLeft"></span> chars left.</span>'.html_safe
    %br/
    =text_area_tag 'message', params[:message], :class=>'required'
    %br/
    %br/
    
    =check_box_tag 'is_primary_nominator', params[:is_primary_nominator], params[:is_primary_nominator]
    %span Yes, I'd like to be the primary contact for the nomination process.
    %br/
    %br/
  =submit_tag("Preview")
%br/
%br/  

:javascript
  $('#reason').limit('500','#reasonCharsLeft');
  $('#message').limit('500','#messageCharsLeft');  

app/views/nominations/_index.html.haml
#contentnav
  -if @current_user
    -if @current_user.is_nominator
      %ul.tabs
        / Give href an ID value of corresponding "tabs-content" <li>'s
        %li
          %a{:href => "#community"} Community
        %li
          %a{:href => "#resources"} Resources
        - nomination_date = "#{Content.insert('nomination_date')}"
        - if lambda {Time.now < Time.parse(nomination_date)}.call
          %li
            %a{:href => "#nomination"} Nomination
        %li
          %a.active{:href => "#partnernews"} Partner News
    -else
      %ul.tabs
        / Give href an ID value of corresponding "tabs-content" <li>'s
        %li
          %a.active{:href => "#welcome"} Welcome
        %li
          %a{:href => "#faq"} FAQs
        %li
          %a{:href => "#application"} Application

%ul.tabs-content
  %li#partnernews.active
    - Content.insert 'partner_news' do |c|
      %h1
        = c.render_field(:title)
      %p
        = c.render_field(:lede)
      - if c.body
        %p
          = c.render_field(:body)
    %iframe{:src => 'http://www.100kpress.com/partner-news/', :style => "width: 650px; height: 1050px;", :scrolling => 'auto'}
  %li#resources
    =render :partial=>'nominations/resources'
  %li#community
    =render :partial=>'nominations/community'
  / end community
  %li#nomination
    -#= Content.insert('nomination_header')
    #nom-header
      %span#nom-text= Content.insert('nomination_header')
    .arrow-down
    #nomination.formShell
      - nomination_date = "#{Content.insert('nomination_date')}"
      = "Unable to display Nomination content as Nomination end date is not available." if nomination_date == ""
      - if nomination_date != ""
        - if lambda {Time.now < Time.parse(nomination_date)}.call
          = Content.insert 'nomination_body'
          = render '/nominations/form'
        -else
          = Content.insert('nomination_thankyou_body')
/ end tabs-content

app/views/nominations/_resources.html.erb
<!-- search box -->
<div style="clear:right;float:left;text-align:right;padding:0px;">
<%= form_tag '/contents/search_resources', :remote=>true %>
<span class="contentsearch" style="text-transform:none;color:#fff;font-family:arial,sans;font-size:11px;">
<input type="text" name="contentsearch" style="width:250px;" /> <input type="submit" class="resourcebutton" value="SEARCH RESOURCES"><br />
</span>

</div>
</form>
<!-- end search box -->


<div id="resource_wrapper">

<% amount = Content.where(:section=>'PORTAL_RESOURCES').size %>
<% Content.where(:section=>'PORTAL_RESOURCES').order(:slug).each do |content| %>
  <%= render :partial=>'contents/resource', :locals=>{:content=>content, :count => amount} %>
  <% amount = amount - 1 %>
<% end %>

</div>

app/views/nominations/_thank_you.haml
.contentShell
  %h1 Dear #{params[:nominator_first_name]}
  %p Thank you for your thoughtful nomination. We invite you to work with #{params[:nominee_first_name]} #{params[:nominee_last_name]} on their application and, in particular, on their bold commitment. Note that the application will be accessible from October 31, 2011 until midnight EST, November 25, 2011 and all approved new partners will be announced in early January 2012. We appreciate your efforts to grow the 100Kin10 movement and truly appreciate the talent that you bring as well.
    
  %p
    Thanks,
    %br/
    The 100Kin10 Team

app/views/nominations/activity.html.erb
<%= link_to '< Portal Home', welcome_index_path %>
<br />
<br />
<h1 id="header">
  ACTIVITY
</h1>
<br />
<h2>Nominated Contacts</h2>
<% if @nominations.empty? %>
  <p>No contacts nominated yet by this Organization.</p>
<% else %>
  <% @nominations.each do |nom| %>
    <div class="leftprofile">
      <h3>Organization Name</h3>
      <%= nom.nominee.organization.name %>
      <h3>Status</h3>
      <% if nom.nominee.application.nil? %>
        <%= "Did Not Apply" %>
      <% else %>
        <%= nom.nominee.application.status %>
      <% end %>
      <h3>Name</h3>
      <%= nom.nominee.full_name %>
      <h3>Email</h3>
      <%= nom.nominee.email %>
      <h3>Nominated On</h3>
      <%= nom.created_at.to_date.strftime('%B %e, %Y') %>
    </div>
    <div class="rightprofile">
      <h3>Reason</h3>
      <%= nom.reason %>
      <h3>Message</h3>
      <%= nom.message %>
    </div>
    <div class="bot">
    </div>
    <br />
  <% end %>
<% end %>

app/views/nominations/create.js.erb
<% if (params[:edit]=="true") %>
  $("#nomination").html("<%= escape_javascript(render :partial=>'index') %>");
<% else %>
  $("#nomination").html("<%= escape_javascript(render :partial=>'thank_you') %>");
<% end %>

app/views/nominations/edit.html.haml
%h1 Editing nomination

= render 'form'

= link_to 'Show', @nomination
\|
= link_to 'Back', nominations_path

app/views/nominations/index.html.haml
=render :partial=>"index"

app/views/nominations/new.html.haml
%h1 New nomination

= render 'form'

= link_to 'Back', nominations_path

app/views/nominations/preview.html.haml
%ul.tabs-content    
  / Give ID that matches HREF of above anchors
  %li#tools
    =image_tag("header-tools.png",:alt => "Tools", :height => "58", :width => "630")
  / end tools
  %li#community
    =image_tag("header-community.png", :alt => "Community", :height => "58", :width => "630")
  / end community
  %li#nomination.active
    #nom-header
      %span#nom-text= Content.insert('nomination_header') 
    .arrow-down
    #nomination.formShell
      %span{:style => "font-size:22px;;color:#222222;font-family:Arial, Helvetica, sans-serif; line-height:28px;"} Dear #{params[:nominee_first_name]}  #{params[:nominee_last_name]},
      %br/
      %p Congratulations on your nomination for partnership in 100Kin10! 100Kin10 represents a diverse, best-in-class network of organizations strategically applying their unique assets to solve a complex, national challenge: 100,000 excellent STEM teachers for our schools over the coming 10 years.
      .hr
      %h1 Here’s a message from #{params[:nominator_first_name]} #{params[:nominator_last_name]}:
      =params[:message].html_safe
      .hr
      %p The online application portal is open and submissions are due on November 25.  You can access the portal with the username and password included at the bottom of this message, and once you begin your application you can save your entry, add to it, and submit it at any point before 11:59pm on November 25th.
      %p To help you craft a competitive submission, we offer the following resources:
      %ul
        %li The FAQ tab on the application portal responds to questions generated during our last round of nominations.
        %li The nominee toolkit, also located on the application portal, can help you craft your commitment.
      %p We also recommend that you reach out for additional guidance and support from the organization(s) that nominated you. And please feel free to contact info@100Kin10.org for any questions you may have. We monitor this mailbox closely and will respond to all inquiries promptly. 
      %p As a reminder, if your application is accepted, you will have access to the 100Kin10 community, including exclusive workshops and resources to increase impact and opportunities for collaboration. You will also participate in a learning and R&D platform created in partnership with the University of Chicago Urban Education Institute (UEI). The platform will spotlight emerging best practices and innovations and, over time, formative data on successful efforts and teacher and student outcomes to enable continuous improvement for all partner organizations. In addition, partners will have the opportunity to apply to work with UEI-deployed research teams. All partners also have access, through a common application form, to funding to support their efforts through the growing 100Kin10 funders’ collaborative.
      %p We have several conference calls scheduled, to help you with any questions you may have regarding your application, or the online portal.   You will receive call times and call-in information in the next few days.
      %p We do hope you will apply for partnership in this growing movement. If you have additional questions or require technical assistance to access the application portal, please contact us at info@100Kin10.org.
      %p Sincerely,
      %p The 100Kin10 Team
      %p
        =link_to("info@100Kin10.org","info@100Kin10.org")
      %span{:style => "font-size:22px;;color:#222222;font-family:Arial, Helvetica, sans-serif; line-height:40px;"} Login Information
      %br/
      Login: #{params[:nominee_email]}
      %br/
      Password: *******
      %br/
      Login URL:
      =link_to('http://100kin10.org/login', 'http://100kin10.org')

      %br
      %br/
      =form_tag('/nominations', :id=>"nomination_form", :remote=>true) do
        /=submit_tag('Back/Edit', :id=>"nomination_back")
        = button_to_function "Back/Edit",'history.back()'
        &nbsp;
        
        =hidden_field_tag 'nominee_first_name', params[:nominee_first_name]      
        =hidden_field_tag 'nominee_last_name', params[:nominee_last_name]      
        =hidden_field_tag 'nominee_title', params[:nominee_title]      
        =hidden_field_tag 'nominee_organization_name', params[:nominee_organization_name]      
        =hidden_field_tag 'nominee_email', params[:nominee_email]      
        =hidden_field_tag 'nominee_phone', params[:nominee_phone]      

        =hidden_field_tag 'nominator_first_name', params[:nominator_first_name]      
        =hidden_field_tag 'nominator_last_name', params[:nominator_last_name]      
        =hidden_field_tag 'nominator_title', params[:nominator_title]      
        =hidden_field_tag 'nominator_organization_name', params[:nominator_organization_name]      
        =hidden_field_tag 'nominator_email', params[:nominator_email]      
        =hidden_field_tag 'nominator_phone', params[:nominator_phone]   
        =hidden_field_tag 'nominator_orgtype', params[:nominator_orgtype]   

        =hidden_field_tag 'reason', params[:reason]      
        =hidden_field_tag 'message', params[:message]      
        =hidden_field_tag 'is_primary_nominator', params[:is_primary_nominator]      
        
        =submit_tag("Submit", :id=>"nomination_submit")
    / end formShell
    / end preview
    / start thanks

app/views/nominations/show.html.haml
%p#notice= notice

%p
  %b Nom org name:
  = @nomination.nom_org_name
%p
  %b Nom first name:
  = @nomination.nom_first_name
%p
  %b Nom last name:
  = @nomination.nom_last_name
%p
  %b Nom title:
  = @nomination.nom_title
%p
  %b Nom email:
  = @nomination.nom_email
%p
  %b Nom phone:
  = @nomination.nom_phone
%p
  %b Your first name:
  = @nomination.your_first_name
%p
  %b Your last name:
  = @nomination.your_last_name
%p
  %b Your title:
  = @nomination.your_title
%p
  %b Your org:
  = @nomination.your_org
%p
  %b Organization type:
  = @nomination.organization_type
%p
  %b Your email:
  = @nomination.your_email
%p
  %b Your phone:
  = @nomination.your_phone
%p
  %b Reason:
  = @nomination.reason
%p
  %b Message:
  = @nomination.message
%p
  %b Is primary:
  = @nomination.is_primary

= link_to 'Edit', edit_nomination_path(@nomination)
\|
= link_to 'Back', nominations_path