config/routes.rb
Goodinc::Application.routes.draw do

  resources :organizations, :only=>[:index, :show, :edit, :update] do
    resources :users do
      member do
        get :reset_password
        get :welcome
      end
    end
    resources :posts, :only => [:create, :destroy, :update] do
      member do
        get :delete
      end
    end
  end

  post "contents/search_resources" => "contents#search_resources", :format=>:js

  resources :applications

  get "/randompartner" => 'pages#randompartner'
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "my_account" => "users#my_account"
  put "update_account" => "users#update_account"

  resources :password_resets

  get '/activity', :controller => 'nominations', :action => 'activity'

  resources :nominations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "welcome/index"



  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#index"
  get "search/donates" => "search#donates"
  get "search/opportunities" => "search#opportunities"

  get "versions/:id/revert" => "versions#revert", as: :version_revert

  resources :users
  resources :sessions

  get "sessions/new"
  get "users/new"

  # Should stay at the bottom so it doesn't clobber any other routes
  match "/page/:slug", :controller=>:pages, :action=>:show, :as=>"page"

  get 'contact_us', :controller => 'contacted_organizations', :action => 'index', :as => :contactus
  post 'contact_us', :controller => 'contacted_organizations', :action => 'save_contact_us', :as => :save_contact_us

  unless Rails.env.production?
    mount UserMailer::Preview => 'email_preview'
  end


  root :to => 'pages#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  PARTNER_STATUSES      = ["partner","funding_partner","new_partner"]
  COMMITMENT_CATEGORIES = ["increase_supply","retain_excellence","build_the_movement"]

  mount_uploader :avatar, AvatarUploader

  has_paper_trail

  attr_accessible :name, :address, :address2, :city, :state_id, :zip, :orgtype_id, :www, :avatar, :other,
    :partner_status, :commitment, :additional_commitment, :primary_contact_id, :secondary_contact_id,
    :commitment_category, :additional_commitment_category,
    :joined_at, :primary_contact_email, :secondary_contact_email,
    :primary_contact_name, :primary_contact_title, :primary_contact_phone
  attr_accessor :primary_contact_phone, :primary_contact_email, :primary_contact_title, :primary_contact_name

  validates :name, :presence=>true

  validates :primary_contact_id, :uniqueness => true, :allow_blank => true

  belongs_to :orgtype
  belongs_to :state
  belongs_to :primary_contact, :class_name=>'User'#, :primary_key=>'primary_contact_id'
  belongs_to :secondary_contact, :class_name=>'Secondary'#, :primary_key=>'secondary_contact_id'

  has_many :posts, :dependent => :destroy
  has_many :users
  has_many :secondaries


  liquid_methods :name

  scope :funding_partners, where(:partner_status=>'funding_partner')
  scope :admin_partners, where(["partner_status=? or partner_status=? or partner_status=?",'funding_partner','partner', 'new_partner'])
  scope :all_partners, where(["partner_status=? or partner_status=?",'funding_partner','partner'])
  scope :regular_partners, where(:partner_status=>'partner')
  scope :full_search, lambda{|n| where(
    ["commitment ~* :search_term or additional_commitment ~* :search_term or name ~* :search_term ", :search_term=>".*#{n}.*"])}
  scope :new_partners, where(:partner_status=>'new_partner')

  before_update :email_partners

  accepts_nested_attributes_for :primary_contact

  def primary_attributes
    primary_contact_id
  end

  def primary_contact_name
    primary_contact.try(:name)
  end

  def primary_contact_email
    primary_contact.try(:email)
  end

  def primary_contact_phone
    primary_contact.try(:phone)
  end

  def primary_contact_title
    primary_contact.try(:title)
  end

  def email_partners
    if self.partner_status.to_s=="partner"
      if self.partner_status.to_s!=Organization.where(:id=>self.id).first.partner_status.to_s
        #testuser = User.where(:email=>"bret@dblsystems.com").first
        User.where(:organization_id=>self.id).each do |partner|
          UserMailer.welcome_partner_new_site(partner).deliver
          #UserMailer.welcome_partner_new_site(testuser).deliver
        end
      end
    end
  end

  def commitment
    self[:commitment].html_safe unless self[:commitment].nil?
  end

  def additional_commitment
    self[:additional_commitment].html_safe unless self[:additional_commitment].nil?
  end

  def save_organization(organization_name, orgtype_id)
    #save for nominee
    self.name = organization_name
    (self.orgtype_id = orgtype_id) if orgtype_id.present?

    self.save!
    return self
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  load_and_authorize_resource

  skip_authorize_resource :only => :edit

  before_filter :require_login, :except=>[:show]
  before_filter :load_resource
  before_filter :authorize_organization, :except=>[:show]
  respond_to :html, :json
  
  def index
  end

  def update
    if @organization.update_attributes(params[:organization])
      redirect_to edit_organization_path(@organization), :notice=>"Organization changes saved."
    else
      redirect_to edit_organization_path(@organization), :notice=>"There was an error saving the changes."
    end
  end

  def edit
    @users = @organization.users  # Added on 13-Mar-2012 to provide Editable Screen to Regular Users in Admin Section.
  end

  def show
    @users = @organization.users  #Added on 9-Mar-2012 to lists users under an organization.
    (redirect_to(login_path) if current_admin_user.blank?) if current_user.blank?
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  private

  def authorize_organization
    redirect_to :root,:notice=>"You are not authorized to edit that organization." unless @organization==@current_user.organization
  end

  def load_resource
    @organization=Organization.find(params[:id])
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def show_field(title, content)
    "<strong>" + title + ":</strong><br>[" + content + "]</br>"
  end
  
end

app/views/organizations/_basic_form.html.erb
<%# Modified to move Organization Edit feature to Admin page %>
<%# Start Modification %>
<%#= semantic_form_for organization do |f| %>
<%#= f.inputs "General Info" do %>
<%#= f.input :avatar, :as=>:file, :label=>"Logo" %>
<%#= f.input :name, :label=>"Organization" %>
<%#= f.input :orgtype, :label=>"Organization Type", :include_blank=>false %>
<%# end %>
<%#= f.inputs "Address" do %>
<%#= f.input :address %>
<%#= f.input :address2 %>
<%#= f.input :city %>
<%#= f.input :state %>
<%#= f.input :zip %>
<%# end %>

<%#= f.inputs "Primary Contact" do %>
<%#= f.input :primary_contact,  :label => "Person", :collection => organization.users %>
<%#= f.input :primary_contact_title, :as => :string, :label => "Title", :input_html => {:disabled => true} %>
<%#= f.input :primary_contact_phone, :as => :string, :label => "Phone", :input_html => {:disabled => true} %>
<%#= f.input :primary_contact_email, :as => :string, :label => "Email", :input_html => {:disabled => true} %>
<%#*<label for="organization_show_contact">%>
<%#= f.check_box :show_contact, :style => "width: 25px;" %>
<%#*Display my contact info in the portal.%>
<%#*</label>%>
<%# end %>
<%#= f.buttons %>
<%# end %>

<%= show_field("Date Joined", @organization.joined_at.strftime('%m/%Y')).html_safe unless @organization.joined_at.blank? %>
<br />
<div class="edit_address">
  <strong>Address:</strong>&nbsp;<%=link_to '[edit]', "#", :title => "Click here to edit", :class => 'edit_org'%><br>
  <div class ="org_type"><%= @organization.address %><br>
    <%= (@organization.address2 + "<br>").html_safe unless @organization.address2.blank? %>
    <%= @organization.city %> <%= @organization.state.abbreviation if @organization.state %> <%= @organization.zip %></div>
  <div class="submit_orgtype" id="parent">
    <%= semantic_form_for @organization do |f| %>
      <%= f.input :address %>
      <%= f.input :address2 %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :zip %>
      <%= f.buttons %>
    <% end %>
  </div>
</div>
<%# Moved from top page to bottom on 13-mar-2012 %>
<%# Start Modification %>
<br/>
<p>
  <% if can? :edit, @organization %>
    <%= link_to "Add New Contact", new_organization_user_path(organization), :class => "button" %>
    <%= link_to "View All Contacts", organization_users_path(@organization), :class => "button" %>
  <% end %>
</p>
<%# End Modification %>
<%# End Modification %>

app/views/organizations/edit.html.erb
<%= link_to '< Portal Home', welcome_index_path %>
<br />
<br />

<h1 id="header">
 ADMIN
</h1>

<br />
<% content_for :dashboard_leftside do %>
  <%= semantic_form_for @organization do |f| %>
    <div id="logobox" style="background:#efefef !important;">
      <%= image_tag f.object.avatar.regular.url %>
    </div>
    <%=  f.input :avatar, :as=>:file, :label=>"Logo" %> <%# Added on 13-Mar-2012 to upload Organization_logo %>
    <br />
    <%= f.buttons %>
    <strong> Organization: </strong>
    <br />
    <%= @organization.name %>
    <br /><br />
    <strong> Organization Type: </strong>
    </br>
    <%= @organization.orgtype.title %>
  <% end %>
<% end %>
<div id="organization_form_wrapper">
  <%= render :partial=>'basic_form', :locals=>{:organization=>@organization} %>
</div>

<script>

  $(document).ready(function(){
    var SAVED_USERS = {};
<% @organization.users.each do |user| %>
      SAVED_USERS["<%= user.id %>"] = <%= raw user.attributes.reject{|k,v| !(['email', 'id', 'phone', 'title'].include?(k.to_s)) }.to_json %>;
      SAVED_USERS["<%= user.id %>"].name = "<%= user.full_name %>";
<% end %>
    $('#organization_primary_contact_id').bind('change', function(){
      var selected = $(this).val();
      var obj = SAVED_USERS[selected];
      if(obj != undefined){
        $("#organization_primary_contact_title").val(obj.title);
        $("#organization_primary_contact_phone").val(obj.phone);
        $("#organization_primary_contact_email").val(obj.email);
      }else{
        $("#organization_primary_contact_title").val('');
        $("#organization_primary_contact_phone").val('');
        $("#organization_primary_contact_email").val('');
      }
    });
    $('.edit_link').bind('click',function(event){
      $('#organization_form_wrapper').toggle();
    });
  });

</script>

<div class="spacer">
  &nbsp;
</div>
<%# Commented on 13-Mar-2012 as this is no longer required as it donot provide any Edit feature%>
<%# Start Comment%>
<!--strong>COMMITMENT</strong-->
<!--p><%#= @organization.commitment %></p-->
<%# unless @organization.additional_commitment.blank? %>
<!--strong>ADDITIONAL COMMITMENT</strong-->
<!--p><%#= @organization.additional_commitment %></p-->
<%# end %>
<%# End Comment%>


<%
=begin
%>
<h2>Organization Newsfeed</h2>

<div id="posts-list">
  <%= render :partial => "posts/list", :locals => { :posts => @organization.posts.order("posts.created_at DESC"), :organization => @organization} %>
</div>
<div class="spacer">
  &nbsp;
</div>
<%
=end
%>

app/views/organizations/index.html.haml
%h1 Organizations#index
%p Find me in app/views/organizations/index.html.haml

app/views/organizations/show.html.erb
<%= link_to '< Portal Home', welcome_index_path %>
<br />
<br />
<% if @organization == @current_user.organization %>
<h1 id="header">
 MY ORGANIZATION
</h1>
<% end %>
<br />
<div class="leftprofile">

  <h2>ORGANIZATION PROFILE</h2>
  
  <% if @organization == @current_user.organization %>
  	<span style='color: #FFC425;'> <%= @organization.name %> </span>
  <% else %>
    <%= @organization.name %>
  <% end %>
  <br />
  <br />
  <%= show_field("Organization Type", @organization.orgtype.title).html_safe unless @organization.orgtype.blank? %>
  <br />
  <%= show_field("Date Joined", @organization.joined_at.strftime('%m/%Y')).html_safe unless @organization.joined_at.blank? %>
  <br />

  <strong>Address:</strong><br />
  <%= @organization.address %><br />
  <%= (@organization.address2 + "<br>").html_safe unless @organization.address2.blank? %>
  <%= @organization.city %> <%= @organization.state.abbreviation if @organization.state %> <%= @organization.zip %>
  <br />
  <br />

  <strong>CONTACTS</strong><br />
  <% if primary_contact=@organization.primary_contact %>
    <%= primary_contact.full_name %>&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size: 12px;">[Admin]</span><br />
    Title:  <%= primary_contact.title %><br />
    <% if primary_contact.show_contact == true %>
      Email:  <%= primary_contact.email %><br />
      Phone:  <%= primary_contact.phone %><br />
    <% end %>
  <% else %>
    Email: <%= @organization.primary_contact_email %><br />
  <% end %>
  <br/>
  <% @users.each do |user|%>
    <% if user.role == 'regular_user' %>
      <%= user.full_name %><br />
      Title:  <%= user.title %><br />
      <% if user.show_contact == true %>
        Email:  <%= user.email %><br />
        Phone:  <%= user.phone %><br />
      <% end %>
    <% end %>
    <br/>
  <% end %>
</div>
<div class="rightprofile">


  <h3> COMMITMENT</h3>
  <%= strip_tags(@organization.commitment) if @organization.commitment.present? %>
  <% unless @organization.additional_commitment.blank? %>
    <h3>ADDITIONAL COMMITMENT</h3>
    <%= @organization.additional_commitment %>
  <% end %>

</div>
<br/>
<div class="spacer">
  &nbsp;
</div>
<%
=begin
%>
<h2>Organization Newsfeed</h2>

<div id="posts-list">
  <%= render :partial => "posts/list", :locals => { :posts => @organization.posts.order("posts.created_at DESC"), :organization => @organization} %>
</div>
<%
=end
%>

app/views/organizations/show.js.erb
$('#link').html('<%= escape_javascript render(:partial=>"layouts/status_newsfeed") %>');
$('#paginator').html('<%= escape_javascript(paginate(@top_posts_by_org, :remote => true).to_s) %>');